=head1 NAME

Gnome2::Bonobo


=head1 METHODS

=head2 boolean = Gnome2::Bonobo-E<gt>B<CHECK_VERSION> ($major, $minor, $micro)

=over

=over

=item * $major (integer) 

=item * $minor (integer) 

=item * $micro (integer) 

=back

=back

=head2 list = Gnome2::Bonobo-E<gt>B<GET_VERSION_INFO> 

=over

=back


=head1 SEE ALSO

L<Gnome2>

=head1 COPYRIGHT

Copyright (C) 2003-2004 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gnome2> for a full notice.


=cut

