=head1 NAME

Gnome2::PasswordDialog

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Container
                      +----Gtk2::Bin
                           +----Gtk2::Window
                                +----Gtk2::Dialog
                                     +----Gnome2::PasswordDialog

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable


=head1 METHODS

=head2 widget = Gnome2::PasswordDialog-E<gt>B<new> ($dialog_title, $message, $username, $password, $readonly_username)

=over

=over

=item * $dialog_title (string) 

=item * $message (string) 

=item * $username (string) 

=item * $password (string) 

=item * $readonly_username (boolean) 

=back

=back

=head2 boolean = $password_dialog-E<gt>B<anon_selected> 

=over

Since: libgnomeui 2.8

=back

=head2 string = $password_dialog-E<gt>B<get_domain> 

=over

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_domain> ($domain)

=over

=over

=item * $domain (string) 

=back

Since: libgnomeui 2.6

=back

=head2 string = $password_dialog-E<gt>B<get_password> 

=over

=back

=head2 $password_dialog-E<gt>B<set_password> ($password)

=over

=over

=item * $password (string) 

=back

=back

=head2 $password_dialog-E<gt>B<set_readonly_domain> ($readonly)

=over

=over

=item * $readonly (boolean) 

=back

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_readonly_username> ($readonly)

=over

=over

=item * $readonly (boolean) 

=back

=back

=head2 passworddialogremember = $password_dialog-E<gt>B<get_remember> 

=over

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_remember> ($remember)

=over

=over

=item * $remember (Gnome2::PasswordDialogRemember) 

=back

Since: libgnomeui 2.6

=back

=head2 boolean = $password_dialog-E<gt>B<run_and_block> 

=over

=back

=head2 $password_dialog-E<gt>B<set_show_domain> ($show)

=over

=over

=item * $show (boolean) 

=back

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_show_password> ($show)

=over

=over

=item * $show (boolean) 

=back

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_show_remember> ($show_remember)

=over

=over

=item * $show_remember (boolean) 

=back

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_show_username> ($show)

=over

=over

=item * $show (boolean) 

=back

Since: libgnomeui 2.6

=back

=head2 $password_dialog-E<gt>B<set_show_userpass_buttons> ($show_userpass_buttons)

=over

=over

=item * $show_userpass_buttons (boolean) 

=back

Since: libgnomeui 2.8

=back

=head2 string = $password_dialog-E<gt>B<get_username> 

=over

=back

=head2 $password_dialog-E<gt>B<set_username> ($username)

=over

=over

=item * $username (string) 

=back

=back


=head1 PROPERTIES

=over

=item 'anonymous' (boolean : readable / writable / private)

anonymous

=item 'domain' (string : readable / writable / private)

domain

=item 'message' (string : readable / writable / private)

message

=item 'message-markup' (string : readable / writable / private)

message-markup

=item 'new-password' (string : readable / writable / private)

new-password

=item 'password' (string : readable / writable / private)

password

=item 'readonly-domain' (boolean : readable / writable / private)

readonly-domain

=item 'readonly-username' (boolean : readable / writable / private)

readonly-username

=item 'remember-mode' (Gnome2::PasswordDialogRemember : readable / writable / private)

remember-mode

=item 'show-domain' (boolean : readable / writable / private)

show-domain

=item 'show-new-password' (boolean : readable / writable / private)

show-new-password

=item 'show-new-password-quality' (boolean : readable / writable / private)

show-new-password-quality

=item 'show-password' (boolean : readable / writable / private)

show-password

=item 'show-remember' (boolean : readable / writable / private)

show-remember

=item 'show-username' (boolean : readable / writable / private)

show-username

=item 'show-userpass-buttons' (boolean : readable / writable / private)

show-userpass-buttons

=item 'username' (string : readable / writable / private)

username

=back


=head1 ENUMS AND FLAGS

=head2 enum Gnome2::PasswordDialogRemember

=over

=item * 'nothing' / 'GNOME_PASSWORD_DIALOG_REMEMBER_NOTHING'

=item * 'session' / 'GNOME_PASSWORD_DIALOG_REMEMBER_SESSION'

=item * 'forever' / 'GNOME_PASSWORD_DIALOG_REMEMBER_FOREVER'

=back



=head1 SEE ALSO

L<Gnome2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>, L<Gtk2::Container>, L<Gtk2::Bin>, L<Gtk2::Window>, L<Gtk2::Dialog>

=head1 COPYRIGHT

Copyright (C) 2003-2004 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gnome2> for a full notice.


=cut

