=head1 NAME

Gnome2::URL


=head1 METHODS

=head2 boolean = Gnome2::URL-E<gt>B<show> ($url)

=over

=over

=item * $url (string) 

=back



May croak with a L<Glib::Error> in $@ on failure.

=back

=head2 boolean = Gnome2::URL-E<gt>B<show_with_env> ($url, $env_ref)

=over

=over

=item * $url (string) 

=item * $env_ref (scalar) 

=back



May croak with a L<Glib::Error> in $@ on failure.

Since: libgnome 2.2

=back


=head1 SEE ALSO

L<Gnome2>

=head1 COPYRIGHT

Copyright (C) 2003-2004 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gnome2> for a full notice.


=cut

