#!/bin/sh
#
# Copyright (C) 2007 Bastien Nocera <bnocera@redhat.com>
# Copyright (C) 2007 David Zeuthen <davidz@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

if [ "$HAL_PROP_KILLSWITCH_TYPE" = "bluetooth" ]; then
    if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "sonypic" ]; then
	hal-system-sonypic setbluetooth $value
	ret=$?
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "hal-system-sonypic returned $ret" >&2
	    exit 1
	fi
	exit 0
    elif [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "dell" ]; then
	if [ "$value" = "true" ]; then
	    hal-system-smbios --bt 1
	    ret=$?
	else
	    hal-system-smbios --bt 0
	    ret=$?
	fi
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "hal-system-smbios returned $ret" >&2
	    exit 1
	fi
    elif [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = thinkpad -a -w "$HAL_PROP_LINUX_SYSFS_PATH" ]; then
        if [ "$value" = "true" ]; then 
	    bit=1; 
	else 
            bit=0; 
        fi
        echo $bit >$HAL_PROP_LINUX_SYSFS_PATH
	ret=$?
        if [ "$ret" != "0" ]; then
            echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "cannot write $bit into $HAL_PROP_LINUX_SYSFS_PATH" >&2
	    exit 1
	fi
    else
	echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
    fi
elif [ "$HAL_PROP_KILLSWITCH_TYPE" = "wlan" ]; then
    if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "dell" ]; then
	if [ "$value" = "true" ]; then
	    hal-system-smbios --wlan 1
	    ret=$?
	else
	    hal-system-smbios --wlan 0
	    ret=$?
	fi
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "$DELL_WCTL returned $ret" >&2
            exit 1
	fi
    else
	echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
    fi
elif [ "$HAL_PROP_KILLSWITCH_TYPE" = "wwan" ]; then
    if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "dell" ]; then 
	if [ "$value" = "true" ]; then
	    hal-system-smbios --wwan 1
	    ret=$?
	else
	    hal-system-smbios --wwan 0
	    ret=$?
	fi
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "hal-system-smbios returned $ret" >&2
            exit 1
	fi
    else
	echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
    fi
else
    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
    echo "Killswitch type not supported" >&2
    exit 1
fi

