#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = remove ] || [ "$1" = upgrade ] && \
   which install-docs >/dev/null 2>&1; then
	install-docs -r fontconfig-user
fi
# End automatically added section
# Automatically added by dh_installdefoma
case "$1" in
	upgrade)
		test -x /usr/bin/defoma-app && \
			/usr/bin/defoma-app clean fontconfig
		;;
	remove)
		test -x /usr/bin/defoma-app && \
			/usr/bin/defoma-app purge fontconfig
		;;
esac
# End automatically added section
