#!/bin/sh

case "$1" in
  purge)
    # Note: We don't remove /etc/network/interfaces
    rm -f /etc/network/run/ifstate

    if [ -L /etc/network/run ] ; then
      rm -f /etc/network/run
    elif [ -d /etc/network/run ] ; then
      rmdir --ignore-fail-on-non-empty /etc/network/run
    fi
    ;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


