#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = purge ]; then
	OLD_DIR=/etc/gconf/schemas
	SCHEMA_FILES="notification-daemon.schemas "
	if [ -d $OLD_DIR ]; then
		for SCHEMA in $SCHEMA_FILES; do
			rm -f $OLD_DIR/$SCHEMA
		done
		rmdir -p --ignore-fail-on-non-empty $OLD_DIR
	fi
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi
# End automatically added section
