#!/bin/sh
set -e

case "$1" in
  configure)
   	killall notification-daemon || true
	 ;;
esac

# Automatically added by dh_gconf
if [ "$1" = "configure" ]; then
	gconf-schemas --register notification-daemon.schemas 
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi
# End automatically added section

