#! /bin/sh

set -e

CONF='/etc/defoma/config/x-ttcidfont-conf.conf'

if [ "$1" = purge ]; then
  rm -f $CONF $CONF~
fi

# Automatically added by dh_installdefoma
if [ "$1" = "purge" ]; then
	rm -rf /var/lib/defoma/x-ttcidfont-conf.d/
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
