#!/bin/sh

set -e

#fix up our old screwup
if dpkg-divert --list  /usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop | grep -q "diversion of /usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop to /usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop.orig by xscreensaver"; then
	rm -f /usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop
	rm -f /usr/share/control-center/Desktop/screensaver-properties.desktop
	dpkg-divert --package xscreensaver --remove --rename --divert \
		/usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop.orig \
		/usr/share/gnome/apps/Settings/Desktop/screensaver-properties.desktop
	dpkg-divert --package xscreensaver --remove --rename --divert \
		/usr/share/control-center/Desktop/screensaver-properties.desktop.orig \
		/usr/share/control-center/Desktop/screensaver-properties.desktop
fi

# Remove /usr/doc symlink
if [ -d /usr/doc -a -h /usr/doc/xscreensaver -a -d /usr/share/doc/xscreensaver ]; then
        rm -f /usr/doc/xscreensaver
fi
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

