#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -x /usr/sbin/suidunregister ]; then
		suidunregister -s xscreensaver /usr/X11R6/bin/xscreensaver
		suidunregister -s xscreensaver /usr/bin/xscreensaver
	fi
	if [ -L /usr/doc/xscreensaver ]; then
		rm -f /usr/doc/xscreensaver
	fi
	;;
esac

# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

