#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -x /usr/sbin/suidunregister ]; then
		suidunregister -s xscreensaver /usr/X11R6/bin/sonar
		suidunregister -s xscreensaver /usr/X11R6/lib/xscreensaver/sonar
		suidunregister -s xscreensaver /usr/lib/xscreensaver/sonar
	fi
	if [ -L /etc/X11/app-defaults/XScreenSaver ]; then
		rm /etc/X11/app-defaults/XScreenSaver
		if [ -f /etc/X11/app-defaults/XScreenSaver-gl ]; then
			ln -sf /etc/X11/app-defaults/XScreenSaver-gl /etc/X11/app-defaults/XScreenSaver
		fi
	fi
	if [ -L /usr/X11R6/lib/X11/app-defaults/XScreenSaver ]; then
		rm /usr/X11R6/lib/X11/app-defaults/XScreenSaver
	fi
	;;
esac


#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -x /usr/sbin/suidunregister ]; then
		suidunregister -s xscreensaver /usr/X11R6/bin/sonar
		suidunregister -s xscreensaver /usr/X11R6/lib/xscreensaver/sonar
		suidunregister -s xscreensaver /usr/lib/xscreensaver/sonar
	fi
	if [ -L /etc/X11/app-defaults/XScreenSaver ]; then
		rm /etc/X11/app-defaults/XScreenSaver
		if [ -f /etc/X11/app-defaults/XScreenSaver-gl ]; then
			ln -sf /etc/X11/app-defaults/XScreenSaver-gl /etc/X11/app-defaults/XScreenSaver
		fi
	fi
	if [ -L /usr/X11R6/lib/X11/app-defaults/XScreenSaver ]; then
		rm /usr/X11R6/lib/X11/app-defaults/XScreenSaver
	fi
	;;
esac


