=head1 NAME

Gnome2::Config::Iterator


=head1 METHODS

=head2 list = $handle-E<gt>B<next> 

=over


Returns the new GnomeConfigIterator, the key, and the value.


=back


=head1 SEE ALSO

L<Gnome2>

=head1 COPYRIGHT

Copyright (C) 2003-2004 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gnome2> for a full notice.


=cut

