#!/bin/sh
set -e

# We install the X server early on so that other packages (e.g. usplash) can
# get at the resolution it configures. It is listed as part of the task,
# which will take care of its removal when the task is removed.
for pkg in xserver-xorg; do
	if apt-cache show "$pkg" >/dev/null 2>&1 &&
	   ! dpkg --get-selections | egrep "^$pkg[[:space:]]+install"; then
		apt-get "$@" -q -y -f install $pkg >/dev/null || true
	fi
done
